=== SamiraShrestha05/LabReport_51/lab3/patientData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="patientData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="patientNo" type="xs:int"/>
              <xs:element name="patientName">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string" minOccurs="0"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="patientDoctorName" type="xs:string"/>
              <xs:element name="patientDisease" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element name="patientLabTest" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SamiraShrestha05/LabReport_51/lab3/patientData.xml
<?xml version="1.0" encoding="UTF-8"?>
<patientData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="patientData.xsd">
  <title>Patient Data</title>
    <entry>
      <patientNo>12345</patientNo>
      <patientName>
        <first>Ram</first>
        <middle>Thapa</middle>
        <last>Magar</last>
      </patientName>
      <patientDoctorName>Hari Shrestha</patientDoctorName>
      <patientDisease>Malaria</patientDisease>
      <patientLabTest>Urine Test</patientLabTest>
      <patientLabTest>Stool Test</patientLabTest>
    </entry>
    <entry>
      <patientNo>12745</patientNo>
      <patientName>
        <first>Raj</first>
        <last>Chand</last>
      </patientName>
      <patientDoctorName>Hari Shrestha</patientDoctorName>
      <patientDisease>Malaria</patientDisease>
      <patientDisease>Cancer</patientDisease>
      <patientLabTest>Urine Test</patientLabTest>
    </entry>
</patientData>
