=== SamiraShrestha05/LabReport_51/lab3/phoneNumbers_externel.dtd
<!ELEMENT phoneNumbers (title,entries)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT entries (entry+)>
    <!ELEMENT entry (name,phone,city)>
    <!ELEMENT name (first, middle?, last)>
      <!ELEMENT first (#PCDATA)>
        <!ELEMENT middle (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT city (#PCDATA)>

=== SamiraShrestha05/LabReport_51/lab3/phoneNumbers.xml
<?xml version="1.0"?>
<!DOCTYPE phoneNumbers SYSTEM "phoneNumbers_externel.dtd">
<phoneNumbers>
    <title>List of phoneNumbers</title>
    <entries>
      <entry>
          <name>
            <first>Rose</first>          
            <last>Chaudhary</last>
          </name>
          <phone>9847694258</phone>
          <city>KTM</city>
      </entry>    
    </entries>
</phoneNumbers>
