=== SamiraShrestha05/LabReport_51/lab3/Q1.bookinfo.dtd
<!ELEMENT bookinfo (book*)>
  <!ELEMENT book (title, author+, ISBNno, publishername, edition, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT ISBNno (#PCDATA)>
    <!ELEMENT publishername (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>

=== SamiraShrestha05/LabReport_51/lab3/Q1.bookinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookinfo SYSTEM "file:///D:/WebTech/xml/Q1.bookinfo.dtd">
<bookinfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebTech/xml/Q1.bookinfo.xsd">
  <book>
    <title>Harry Potter</title>
    <author>J. K. Rowling</author>
    <ISBNno>978-0-306-40615-7</ISBNno>
    <publishername>Bloomsbury Publishing</publishername>
    <edition>1</edition>
    <price>60</price>
  </book>
  </bookinfo>
