=== SamiraShrestha05/LabReport_51/lab3/Q4.book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:attributeGroup name="authorAtt">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="phone" type="xs:string"/>
    <xs:attribute name="email" type="xs:string"/>  
</xs:attributeGroup>
  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="firstName" type="xs:string"/>
                          <xs:element name="middleName" type="xs:string"/>
                          <xs:element name="lastName" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="title" type="xs:string" default="ms"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="phone" type="xs:string"/>
                    <xs:element name="email" type="xs:string"/>
                  </xs:sequence>
                  <xs:attributeGroup ref="authorAtt"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="pageNo" type="xs:integer"/>
              <xs:element name="price">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="600"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ISBN" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SamiraShrestha05/LabReport_51/lab3/Q4.books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "file:///D:/WebTech/xml/Q4.books.dtd">
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebTech/xml/Q4.book.xsd">
  <book ISBN="">
    <title></title>
    <author name="Robert Galbraith" phone="2071234567" email="info@jkrowling.com">
      <name title="ms">
        <firstName>Joanne</firstName>
        <middleName>Kathleen</middleName>
        <lastName>Rowling</lastName>
      </name>
      <phone>2071234567</phone>
      <email>info@jkrowling.com</email>
      </author>
    <pageNo>223</pageNo>
    <price>600</price>
  </book>
</books>
